/**
 * Role Based Access Control (RBAC) Configuration
 * 
 * This file defines access permissions for different user roles across various pages.
 * Each role has a table with switches (true/false) for each page.
 */

export interface PagePermissions {
  [page: string]: boolean;
}

export interface RBACConfig {
  [role: string]: PagePermissions;
}

const rbacDefaultConfig: RBACConfig = {
  // Default permissions (applied before checking user roles)
  default: {
    Dashboard: false,
    Performance: false,
    Bookings: false,
    Listings: false,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: false,
    LearningHubAdmin: false,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: false,
    VolunteerCreation: false,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: false,
    Roles: true,
  },
  
  // Steward role permissions
  steward: {
    Dashboard: true,
    Performance: true,
    Bookings: true,
    Listings: true,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: false,
    LearningHubAdmin: false,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: true,
    VolunteerCreation: true,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: true,
    Roles: true,
  },
  
  // Space host role permissions
  'space-host': {
    Dashboard: true,
    Performance: true,
    Bookings: true,
    Listings: true,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: false,
    LearningHubAdmin: false,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: false,
    VolunteerCreation: false,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: true,
    Roles: true,
  },
  
  // Community curator role permissions
  'community-curator': {
    Dashboard: true,
    Performance: true,
    Bookings: true,
    Listings: false,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: false,
    LearningHubAdmin: false,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: false,
    VolunteerCreation: false,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: false,
    Roles: true,
  },
  
  // Member role permissions
  member: {
    Dashboard: false,
    Performance: false,
    Bookings: false,
    Listings: false,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: false,
    LearningHubAdmin: false,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: false,
    VolunteerCreation: false,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: false,
    Roles: true,
  },
  
  // Content creator role permissions
  'content-creator': {
    Dashboard: true,
    Performance: true,
    Bookings: false,
    Listings: false,
    Food: false,
    UserManagement: false,
    PlatformSettings: false,
    RBAC: false,
    LearningHub: true,
    LearningHubCreate: true,
    AffiliateSettings: false,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: false,
    VolunteerCreation: false,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: false,
    RoleCreation: false,
    Roles: true,
  },
  
  // Admin role permissions (has access to everything)
  admin: {
    Dashboard: true,
    Performance: true,
    Bookings: true,
    Listings: true,
    Food: true,
    UserManagement: true,
    PlatformSettings: true,
    RBAC: true,
    LearningHub: true,
    LearningHubCreate: true,
    LearningHubAdmin: true,
    AffiliateSettings: true,
    Invest: true,
    Community: true,
    Subscriptions: true,
    Events: true,
    Volunteer: true,
    Residence: true,
    Stay: true,
    MyBookings: true,
    Referrals: true,
    Governance: true,
    EventCreation: true,
    VolunteerCreation: true,
    Resources: true,
    SupportUs: true,
    Token: true,
    Blog: true,
    TokenSales: true,
    RoleCreation: true,
    Roles: true,
  },
};

export default rbacDefaultConfig;
