const models = {
  channel: [
    {
      name: 'name',
      label: 'Channel Name',
      type: 'text',
      placeholder: 'Mauritius co-housing',
      required: true,
    },
    {
      name: 'description',
      label: 'Description',
      type: 'longtext',
      placeholder: 'A place to co-conspire',
    },
    {
      name: 'visibility',
      label: 'Visibility',
      type: 'select',
      options: [
        { label: 'Public', value: 'public' },
        { label: 'Private', value: 'private' },
      ],
    },
  ],
  user: [
    {
      name: 'screenname',
      label: 'Full name',
      type: 'text',
      placeholder: 'John Snow',
      required: true,
    },
    {
      name: 'settings.skills',
      label: 'What skills do you feel comfortable with?',
      type: 'tags',
      placeholder: 'Woodworking, cooking',
    },
    {
      name: 'settings.mattress',
      type: 'select',
      label: 'How do you like your mattress?',
      options: [
        { label: 'Soft', value: 'soft' },
        { label: 'Medium', value: 'medium' },
        { label: 'Hard', value: 'hard' },
      ],
    },
    {
      name: 'settings.newsletter_weekly',
      label: 'Weekly summary email',
      type: 'switch',
    },
  ],

  event: [
    {
      name: 'name',
      className: 'text-4xl font-bold',
      label: 'Event title',
      type: 'text',
      placeholder: 'My event',
      required: true,
      tab: 'general',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'longtext',
      placeholder: 'A gathering around...',
      tab: 'general',
    },
    {
      name: 'start',
      label: 'When does the event start?',
      type: 'datetime',
      required: true,
      tab: 'general',
    },
    {
      name: 'end',
      label: 'When does the event end?',
      type: 'datetime',
      required: true,
      tab: 'general',
    },
    {
      name: 'virtual',
      label: 'Is this a virtual event?',
      type: 'switch',
      defaultValue: false,
      tab: 'general',
    },
    {
      name: 'blocksBookingCalendar',
      label: 'Should this event block the booking calendar?',
      type: 'switch',
      defaultValue: false,
      tab: 'general',
    },
    {
      name: 'location',
      label: 'Event URL',
      defaultValue: '',
      type: 'text',
      placeholder: 'https://zoom.com/wakeup',
      tab: 'general',
      showIf: [
        {
          field: 'virtual',
          value: true,
        },
      ],
    },
    {
      name: 'address',
      label: 'Event location',
      defaultValue: '',
      type: 'text',
      placeholder: '23 Maple St, 10100 San Francisco',
      tab: 'general',
      showIf: [
        {
          field: 'virtual',
          value: false,
        },
      ],
    },
    {
      name: 'recording',
      label: 'Youtube recording URL',
      defaultValue: '',
      type: 'text',
      tab: 'general',
      placeholder: 'https://www.youtube.com/watch?v=r2-Ux4RRMKE',
    },
    {
      name: 'visibility',
      label: 'Visibility',
      type: 'select',
      options: [
        { label: 'Public', value: 'public' },
        { label: 'Private', value: 'private' },
      ],
      tab: 'general',
    },
    {
      name: 'paid',
      label: 'Is this a paid event?',
      type: 'switch',
      tab: 'tickets',
      defaultValue: false,
    },
    {
      name: 'ticketOptions',
      label: 'Ticket options',
      type: 'ticketOptions',
      tab: 'tickets',
      showIf: [
        {
          field: 'paid',
          value: true,
        },
        {
          field: 'ticket',
          value: '',
        },
      ],
    },
    {
      name: 'discounts',
      label: 'Discount codes',
      type: 'discounts',
      tab: 'tickets',
      showIf: [
        {
          field: 'paid',
          value: true,
        },
      ],
    },
    {
      name: 'stripePub',
      label: 'Custom Stripe Public Key',
      type: 'text',
      tab: 'tickets',
    },
    {
      name: 'stripeKey',
      label: 'Custom Stripe Private Key',
      type: 'text',
      tab: 'tickets',
    },
    {
      name: 'fields',
      label: 'Custom questions',
      type: 'fields',
      tab: 'advanced',
    },
    {
      name: 'ticket',
      label: 'Use External Ticketing URL',
      defaultValue: '',
      type: 'text',
      toggleFeature: true,
      placeholder: 'eventbrite.com/my-ticket',
      tab: 'advanced',
    },
    {
      name: 'password',
      label: 'Event password',
      tab: 'advanced',
      type: 'text',
      placeholder: '(If set, user will need the password to see)',
    },
    {
      name: 'participationGuideUrl',
      label: 'Participation guide',
      tab: 'advanced',
      type: 'text',
      placeholder: 'https://event.com/participation',
    },
    {
      name: 'slug',
      label: 'Slug',
      public: true,
      required: true,
      index: 1,
      unique: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'foodOption',
      label: 'Food option',
      ownerVisible: true,
      editable: true,
      default: [],
      type: 'select',
      options: [
        { label: 'No food', value: 'no_food' },
        { label: 'Basic food', value: 'basic' },
        { label: 'Chef cooked food', value: 'chef' },
        { label: 'Let guests choose', value: 'default' },
      ],
    },
  ],

  lesson: [
    {
      name: 'title',
      className: 'text-4xl font-bold',
      label: 'Lesson title',
      type: 'text',
      placeholder: 'Enter lesson name',
      required: true,
      tab: 'general',
    },
    {
      name: 'summary',
      label: 'Summary',
      type: 'text',
      placeholder: 'Lesson summary...',
      tab: 'general',
    },
    {
      name: 'paid',
      label: 'Is this a paid lesson?',
      type: 'switch',
      tab: 'general',
      defaultValue: true,
    },
    {
      name: 'previewVideo',
      label: 'Preview video URL (Vimeo or Youtube)',
      defaultValue: '',
      type: 'text',
      tab: 'general',
      placeholder: 'enter preview video URL...',
    },
    {
      name: 'fullVideo',
      label: 'Full video URL (Vimeo or Youtube)',
      defaultValue: '',
      type: 'text',
      tab: 'general',
      placeholder: 'enter full video URL...',
    },
    {
      name: 'photo',
      label: 'Photo',
      public: true,
      editable: true,
      tab: 'general',
      type: 'photos',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'longtext',
      placeholder: 'Lesson full text',
      tab: 'general',
    },
    {
      name: 'category',
      label: 'Category',
      public: true,
      editable: true,
      required: true,
      type: 'text',
    },
    {
      name: 'slug',
      label: 'Slug',
      public: true,
      required: true,
      index: 1,
      unique: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'tags',
      label: 'Tags',
      type: 'tags',
      placeholder: 'Add tag',
    },
  ],
  article: [
    {
      name: 'title',
      className: 'text-4xl font-bold',
      label: 'Article title',
      type: 'text',
      placeholder: 'Enter article title',
      required: true,
      tab: 'general',
    },
    {
      name: 'photo',
      label: 'Photo',
      public: true,
      editable: true,
      tab: 'general',
      type: 'photos',
    },
    {
      name: 'summary',
      label: 'Summary',
      type: 'text',
      placeholder: 'Article summary...',
      tab: 'general',
    },
    {
      name: 'html',
      label: 'html',
      type: 'longtext',
      placeholder: 'Article full text...',
      tab: 'general',
    },

    {
      name: 'category',
      label: 'Category',
      public: true,
      editable: true,
      required: true,
      type: 'text',
    },
    {
      name: 'tags',
      label: 'Tags',
      type: 'tags',
      placeholder: 'Add tag',
    },
  ],
  task: [
    {
      name: 'title',
      label: 'Title',
      type: 'text',
      placeholder: 'Plant tomatoes in the garden',
      required: true,
    },
    {
      name: 'description',
      label: 'Summary of work',
      type: 'longtext',
      placeholder: `- Establish farming beds
- Make soil
- Plant seeds`,
    },
    {
      name: 'due',
      label: 'Due date',
      type: 'date',
      required: false,
      default: null,
    },
    {
      name: 'tags',
      label: 'Skills required',
      type: 'tags',
      placeholder: 'Add skill',
    },
    {
      name: 'visibility',
      label: 'Visibility',
      type: 'select',
      options: [
        { label: 'Public (visible to anyone)', value: 'public' },
        { label: 'Private (only members can apply)', value: 'private' },
      ],
    },
    { name: 'rewards', label: 'Reward', type: 'currency' },
  ],
  listing: [
    {
      name: 'name',
      label: 'Listing name',
      type: 'text',
      placeholder: 'Spacious loft',
      required: true,
      tab: 'general',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'longtext',
      placeholder: 'A beautiful treehouse loft with hot tub.',
      tab: 'general',
    },
    { name: 'photos', label: 'Photos', type: 'photos', tab: 'photos' },
    {
      name: 'private',
      label: 'Is this a private space?',
      type: 'switch',
      defaultValue: false,
      tab: 'general',
    },
    {
      name: 'kitchen',
      label: 'Does the space have a private kitchen?',
      type: 'switch',
      defaultValue: false,
    },
    {
      name: 'bathroom',
      label: 'Does the space have a private bathroom?',
      type: 'switch',
      defaultValue: false,
    },
    {
      name: 'rooms',
      label: 'Number of rooms',
      type: 'number',
      min: 1,
      required: false,
    },
    {
      name: 'beds',
      label: 'Number of beds',
      type: 'number',
      min: 1,
      required: false,
    },
    {
      name: 'fiatPrice',
      label: 'Rental price per night (fiat)',
      type: 'currency',
      placeholder: '10.00',
      required: true,
      tab: 'prices',
    },
    {
      name: 'fiatHourlyPrice',
      label: 'Hourly rental price (fiat)',
      type: 'currency',
      placeholder: '10.00',
      required: false,
      tab: 'prices',
    },
    {
      name: 'tokenPrice',
      label: 'Rental price per night (credits or tokens)',
      type: 'currency',
      placeholder: '10.00',
      required: true,
      tab: 'prices',
    },
    {
      name: 'tokenHourlyPrice',
      label: 'Hourly Rental price (credits or tokens)',
      type: 'currency',
      placeholder: '10.00',
      required: false,
      tab: 'prices',
    },
    {
      name: 'quantity',
      label: 'Quantity available',
      type: 'number',
      min: 1,
      required: false,
    },
    {
      name: 'availableFor',
      label: 'Available for',
      ownerVisible: true,
      editable: true,
      enum: ['volunteer', 'guests', 'team', 'events'],
      default: [],
      type: 'multi-select',
      options: ['guests', 'volunteer', 'team', 'events'],
    },
    {
      name: 'priceDuration',
      label: 'Booking duration unit',
      default: 'public',
      type: 'select',
      options: [
        { label: 'Night', value: 'night' },
        { label: 'Hour', value: 'hour' },
        // { label: 'Half a day', value: 'half-day' },
      ],
    },
    {
      name: 'workingHoursStart',
      label: 'Start of working hours',
      type: 'number',
      placeholder: '10',
      required: false,
    },
    {
      name: 'workingHoursEnd',
      label: 'End of working hours',
      type: 'number',
      placeholder: '20',
      required: false,
    },
  ],
  food: [
    {
      name: 'name',
      label: 'Food option name',
      type: 'text',
      placeholder: 'Basic food',
      required: true,
      tab: 'general',
    },
    {
      name: 'description',
      label: 'Description',
      type: 'longtext',
      placeholder: 'Food option description',
      tab: 'general',
    },
    { name: 'photos', label: 'Photos', type: 'photos', tab: 'photos' },
  ],
  booking: [
    { name: 'start', label: 'Start date', type: 'date' },
    { name: 'end', label: 'End', type: 'date' },
  ],
  application: [
    {
      name: 'inspiration',
      label:
        'What is the most inspiring thing you`ve seen recently? Any events/community/book/project etc.',
      type: 'longtext',
      placeholder: 'Project Heart in Tulum',
    },
    {
      name: 'home',
      label: 'What does home mean to you?',
      type: 'longtext',
      placeholder: '',
    },
    {
      name: 'gift',
      label: 'What will you bring to the community?',
      type: 'longtext',
      placeholder:
        'Any special skills? Workshops you can give? Can you help with construction? Or gardening?',
    },
    {
      name: 'name',
      label: 'What is your name?',
      type: 'text',
      placeholder: 'John Snow',
      required: true,
    },
    {
      name: 'phone',
      label: 'What is your phone number? (include country code)',
      type: 'phone',
      placeholder: '+35108892645',
    },
    {
      name: 'email',
      label: 'What is your email?',
      type: 'text',
      placeholder: 'you@awesomeproject.org',
      required: true,
    },
    {
      name: 'dream',
      label: 'What do you dream of?',
      type: 'longtext',
      placeholder: '',
    },
  ],
  volunteer: [
    {
      name: 'name',
      label: 'Title',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'category',
      label: 'Category',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'photo',
      label: 'Photo',
      public: true,
      editable: true,
      type: 'photos',
    },
    {
      name: 'slug',
      label: 'Slug',
      public: true,
      required: true,
      index: 1,
      unique: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'description',
      label: 'Description',
      public: true,
      editable: true,
      type: 'longtext',
    },
    {
      name: 'start',
      label: 'Start date',
      public: true,
      editable: true,
      type: 'datetime',
    },
    {
      name: 'end',
      label: 'End date',
      public: true,
      editable: true,
      type: 'datetime',
    },
    {
      name: 'visibility',
      label: 'Visibility',
      ownerVisible: true,
      editable: true,
      enum: ['public', 'custom', 'private', 'secret'],
      default: 'public',
      type: 'select',
      options: [
        { label: 'Public', value: 'public' },
        { label: 'Private', value: 'private' },
      ],
    },
  ],
  bookingConfig: [
    {
      name: 'utilityFiatCur',
      label: 'Utility currency',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'utilityFiatVal',
      label: 'Utility price',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'utilityDayFiatCur',
      label: 'Utility day currency',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'utilityDayFiatVal',
      label: 'Utility day price',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'utilityTokenVal',
      label: 'Token utility price',
      public: true,
      editable: true,
      step: 0.01,
      type: 'number',
    },
    {
      name: 'utilityTokenCur',
      label: 'Token utility currency',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'checkinTime',
      label: 'Check in time',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'checkoutTime',
      label: 'Check out time',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'maxDuration',
      label: 'Max booking duration',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'minDuration',
      label: 'Min booking duration',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'volunteerCommitment',
      label: 'Volunteer commitment',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'conditionsMemberMaxDuration',
      label: 'Max member booking duration',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'conditionsMemberMaxBookingHorizon',
      label: 'Max member booking horizon',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'conditionsGuestMaxDuration',
      label: 'Max guest booking duration',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'conditionsGuestMaxBookingHorizon',
      label: 'Max guest booking horizon',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'discountsDaily',
      label: 'Discount daily stay',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'discountsWeekly',
      label: 'Discount weekly stay',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'discountsMonthly',
      label: 'Discount monthly stay',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'seasonsHighStart',
      label: 'High season first month',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'seasonsHighEnd',
      label: 'High season last month',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'seasonsHighModifier',
      label: 'High season modifier',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'cancellationPolicyLastday',
      label: 'Cancellation policy last day refund fraction (0.5 equals 50%)',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'cancellationPolicyLastweek',
      label: 'Cancellation policy last week refund fraction (0.5 equals 50%)',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'cancellationPolicyLastmonth',
      label: 'Cancellation policy last month refund fraction (0.5 equals 50%)',
      public: true,
      editable: true,
      type: 'number',
    },
    {
      name: 'cancellationPolicyDefault',
      label: 'Cancellation policy default refund fraction',
      public: true,
      editable: true,
      type: 'number',
    },
  ],
  generalConfig: [
    {
      name: 'platformShortName',
      label: 'Platform short name',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'platformFullName',
      label: 'Platform full name',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'legalAddress',
      label: 'Legal address',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'domain',
      label: 'Domain',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'clientSupportEmail',
      label: 'Client support email',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'instagramUrl',
      label: 'Instagram account URL',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'facebookUrl',
      label: 'Facebook account URL',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'twitterUrl',
      label: 'Twitter account URL',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'locationLat',
      label: 'Location latitude',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'locationLon',
      label: 'Location longitude',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'visitorsGuide',
      label: 'Link to visitor’s guide',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'facebookPixelId',
      label: 'Facebook pixel id',
      public: true,
      editable: true,
      type: 'text',
    },
    {
      name: 'faqsGoogleSheetId',
      label: 'FAQ Google Sheet id',
      public: true,
      editable: true,
      type: 'text',
    },
  ],
};

export default models;
