// Generated by closer-api-ts scripts/emit-types.ts from commit cf36c1e; do not edit.
import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server';

// context.d.ts
export type AccessToken = {
    sub: string;
    type?: string;
    claims: string[];
    platform?: unknown;
    viewChannels: string[];
    manageChannels: string[];
    env?: string;
    iat: number;
    exp?: number;
};
export type Context = {
    user: AccessToken | null;
};
export type FlattenedZodError = {
    formErrors: string[];
    fieldErrors: Record<string, string[] | undefined>;
};

// root.d.ts
export declare const appRouter: import("@trpc/server").TRPCBuiltRouter<{
    ctx: Context;
    meta: object;
    errorShape: {
        message: string;
        code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
        data: {
            code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
            httpStatus: number;
            path?: string;
            stack?: string;
            zodError: FlattenedZodError | null;
        };
    };
    transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
    food: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            message: string;
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            })[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                search: string;
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                name?: string | number | boolean | null | undefined;
                photos?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                slug?: string | number | boolean | null | undefined;
                description?: string | number | boolean | null | undefined;
                price?: string | number | boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: string | number | boolean | null | undefined;
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                search: string;
                data: {
                    name?: string | number | boolean | null | undefined;
                    photos?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    slug?: string | number | boolean | null | undefined;
                    description?: string | number | boolean | null | undefined;
                    price?: string | number | boolean | null | undefined;
                    availableFor?: unknown[] | null | undefined;
                    isDefault?: string | number | boolean | null | undefined;
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | null | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                };
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
}>>;
export type AppRouter = typeof appRouter;

// index.d.ts
export type RouterInputs = inferRouterInputs<AppRouter>;
export type RouterOutputs = inferRouterOutputs<AppRouter>;
export declare const createCaller: import("@trpc/server").TRPCRouterCaller<{
    ctx: Context;
    meta: object;
    errorShape: {
        message: string;
        code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
        data: {
            code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
            httpStatus: number;
            path?: string;
            stack?: string;
            zodError: FlattenedZodError | null;
        };
    };
    transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
    food: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            message: string;
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            })[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                search: string;
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                name?: string | number | boolean | null | undefined;
                photos?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                slug?: string | number | boolean | null | undefined;
                description?: string | number | boolean | null | undefined;
                price?: string | number | boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: string | number | boolean | null | undefined;
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                search: string;
                data: {
                    name?: string | number | boolean | null | undefined;
                    photos?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    slug?: string | number | boolean | null | undefined;
                    description?: string | number | boolean | null | undefined;
                    price?: string | number | boolean | null | undefined;
                    availableFor?: unknown[] | null | undefined;
                    isDefault?: string | number | boolean | null | undefined;
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | null | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                };
            };
            output: Record<string, never> | {
                name?: string | null | undefined;
                photos: (string | null)[] | null;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor: unknown[] | null;
                isDefault: boolean | null;
                visibility: string | null;
                channel?: string | null | undefined;
                visibleBy: (string | null)[] | null;
                createdBy: string | null;
                interaction?: string | null | undefined;
                updated: string | null;
                created: string | null;
                attributes: unknown[] | null;
                managedBy: (string | null)[] | null;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
}>>;
