// Generated by closer-api-ts scripts/emit-types.ts from commit 634e377; do not edit.
import type { inferRouterInputs, inferRouterOutputs } from '@trpc/server';

// context.d.ts
export type AccessToken = {
    sub: string;
    type?: string;
    claims: string[];
    platform?: unknown;
    viewChannels: string[];
    manageChannels: string[];
    env?: string;
    iat: number;
    exp?: number;
};
export type Context = {
    user: AccessToken | null;
};
export type FlattenedZodError = {
    formErrors: string[];
    fieldErrors: Record<string, string[] | undefined>;
};

// root.d.ts
export declare const appRouter: import("@trpc/server").TRPCBuiltRouter<{
    ctx: Context;
    meta: object;
    errorShape: {
        code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
        message: string;
        data: {
            code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
            httpStatus: number;
            path?: string;
            stack?: string;
            zodError: FlattenedZodError | null;
        };
    };
    transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
    article: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            message: string;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
                excludeCategory?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
            })[];
            meta: object;
        }>;
        count: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                excludeCategory?: string | undefined;
            } | undefined;
            output: number;
            meta: object;
        }>;
        search: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                keyword: string;
            };
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
            })[];
            meta: object;
        }>;
        tags: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                keyword?: string | undefined;
            } | undefined;
            output: string[];
            meta: object;
        }>;
        related: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                id: string;
                category?: string | null | undefined;
                tags: (string | null)[];
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
                authorInfo: {
                    screenname: string;
                    photo: string;
                    _id: string;
                };
            }[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                idOrSlug: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                category?: string | number | boolean | null | undefined;
                tags?: (string | number | boolean | null)[] | null | undefined;
                html?: string | number | boolean | null | undefined;
                editorState?: string | number | boolean | null | undefined;
                photo?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                photoUrl?: string | number | boolean | null | undefined;
                title: string | number | boolean;
                summary?: string | number | boolean | undefined;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
                data: {
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | undefined;
                    title?: string | number | boolean | null | undefined;
                    slug?: string | number | boolean | undefined;
                    category?: string | number | boolean | null | undefined;
                    tags?: (string | number | boolean | null)[] | null | undefined;
                    html?: string | number | boolean | null | undefined;
                    editorState?: string | number | boolean | null | undefined;
                    summary?: string | number | boolean | null | undefined;
                    photo?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    photoUrl?: string | number | boolean | null | undefined;
                };
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                html?: string | null | undefined;
                editorState?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                photoUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
    food: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            message: string;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: boolean | null | undefined;
                _id: string;
            })[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                idOrSlug: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: boolean | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                name?: string | number | boolean | null | undefined;
                photos?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                slug?: string | number | boolean | undefined;
                description?: string | number | boolean | null | undefined;
                price?: string | number | boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: string | number | boolean | null | undefined;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: boolean | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                idOrSlug: string;
                data: {
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | undefined;
                    name?: string | number | boolean | null | undefined;
                    photos?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    slug?: string | number | boolean | undefined;
                    description?: string | number | boolean | null | undefined;
                    price?: string | number | boolean | null | undefined;
                    availableFor?: unknown[] | null | undefined;
                    isDefault?: string | number | boolean | null | undefined;
                };
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                price?: number | null | undefined;
                availableFor?: unknown[] | null | undefined;
                isDefault?: boolean | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
    lesson: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            message: string;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
                category?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                isDraft?: boolean | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                description?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                previewVideo?: string | null | undefined;
                fullVideo?: string | null | undefined;
                variant?: string | null | undefined;
                price?: unknown;
                modules?: unknown;
                access?: (string | null)[] | null | undefined;
                liveSessionUrl?: string | null | undefined;
                _id: string;
            })[];
            meta: object;
        }>;
        count: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                category?: string | undefined;
            } | undefined;
            output: number;
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                idOrSlug: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                isDraft?: boolean | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                description?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                previewVideo?: string | null | undefined;
                fullVideo?: string | null | undefined;
                variant?: string | null | undefined;
                price?: unknown;
                modules?: unknown;
                access?: (string | null)[] | null | undefined;
                liveSessionUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                isDraft?: string | number | boolean | null | undefined;
                title: string | number | boolean | null;
                slug?: string | number | boolean | undefined;
                category?: string | number | boolean | null | undefined;
                tags?: (string | number | boolean | null)[] | null | undefined;
                description?: string | number | boolean | null | undefined;
                summary?: string | number | boolean | null | undefined;
                photo?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                previewVideo?: string | number | boolean | null | undefined;
                fullVideo?: string | number | boolean | null | undefined;
                variant?: string | number | boolean | null | undefined;
                price?: unknown[] | Record<string, unknown> | null | undefined;
                modules?: unknown[] | Record<string, unknown> | null | undefined;
                access?: (string | number | boolean | null)[] | null | undefined;
                liveSessionUrl?: string | number | boolean | null | undefined;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                isDraft?: boolean | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                description?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                previewVideo?: string | null | undefined;
                fullVideo?: string | null | undefined;
                variant?: string | null | undefined;
                price?: unknown;
                modules?: unknown;
                access?: (string | null)[] | null | undefined;
                liveSessionUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
                data: {
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | undefined;
                    isDraft?: string | number | boolean | null | undefined;
                    category?: string | number | boolean | null | undefined;
                    tags?: (string | number | boolean | null)[] | null | undefined;
                    description?: string | number | boolean | null | undefined;
                    photo?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    previewVideo?: string | number | boolean | null | undefined;
                    fullVideo?: string | number | boolean | null | undefined;
                    variant?: string | number | boolean | null | undefined;
                    price?: unknown[] | Record<string, unknown> | null | undefined;
                    modules?: unknown[] | Record<string, unknown> | null | undefined;
                    access?: (string | number | boolean | null)[] | null | undefined;
                    liveSessionUrl?: string | number | boolean | null | undefined;
                    title?: string | number | boolean | null | undefined;
                    slug?: string | number | boolean | undefined;
                    summary?: string | number | boolean | null | undefined;
                };
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                isDraft?: boolean | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                category?: string | null | undefined;
                tags?: (string | null)[] | null | undefined;
                description?: string | null | undefined;
                summary?: string | null | undefined;
                photo?: string | null | undefined;
                previewVideo?: string | null | undefined;
                fullVideo?: string | null | undefined;
                variant?: string | null | undefined;
                price?: unknown;
                modules?: unknown;
                access?: (string | null)[] | null | undefined;
                liveSessionUrl?: string | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
    listing: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            message: string;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
                availableFor?: string[] | undefined;
            } | undefined;
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                category?: string | null | undefined;
                photo?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                priceDuration?: string | null | undefined;
                workingHoursStart?: number | null | undefined;
                workingHoursEnd?: number | null | undefined;
                fiatPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                fiatHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                workingHoursFrom?: number | null | undefined;
                workingHoursTo?: number | null | undefined;
                rooms?: number | null | undefined;
                beds?: number | null | undefined;
                quantity?: number | null | undefined;
                private?: boolean | null | undefined;
                kitchen?: boolean | null | undefined;
                bathroom?: boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                _id: string;
            })[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                idOrSlug: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                category?: string | null | undefined;
                photo?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                priceDuration?: string | null | undefined;
                workingHoursStart?: number | null | undefined;
                workingHoursEnd?: number | null | undefined;
                fiatPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                fiatHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                workingHoursFrom?: number | null | undefined;
                workingHoursTo?: number | null | undefined;
                rooms?: number | null | undefined;
                beds?: number | null | undefined;
                quantity?: number | null | undefined;
                private?: boolean | null | undefined;
                kitchen?: boolean | null | undefined;
                bathroom?: boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                name?: string | number | boolean | null | undefined;
                category?: string | number | boolean | null | undefined;
                photo?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                photos?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                slug?: string | number | boolean | undefined;
                description?: string | number | boolean | null | undefined;
                priceDuration?: string | number | boolean | null | undefined;
                workingHoursStart?: string | number | boolean | null | undefined;
                workingHoursEnd?: string | number | boolean | null | undefined;
                fiatPrice?: {
                    [x: string]: unknown;
                    val?: string | number | boolean | null | undefined;
                    cur?: string | number | boolean | null | undefined;
                } | null | undefined;
                fiatHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | boolean | null | undefined;
                    cur?: string | number | boolean | null | undefined;
                } | null | undefined;
                tokenPrice?: {
                    [x: string]: unknown;
                    val?: string | number | boolean | null | undefined;
                    cur?: string | number | boolean | null | undefined;
                } | null | undefined;
                tokenHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | boolean | null | undefined;
                    cur?: string | number | boolean | null | undefined;
                } | null | undefined;
                workingHoursFrom?: string | number | boolean | null | undefined;
                workingHoursTo?: string | number | boolean | null | undefined;
                rooms?: string | number | boolean | null | undefined;
                beds?: string | number | boolean | null | undefined;
                quantity?: string | number | boolean | null | undefined;
                private?: string | number | boolean | null | undefined;
                kitchen?: string | number | boolean | null | undefined;
                bathroom?: string | number | boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                category?: string | null | undefined;
                photo?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                priceDuration?: string | null | undefined;
                workingHoursStart?: number | null | undefined;
                workingHoursEnd?: number | null | undefined;
                fiatPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                fiatHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                workingHoursFrom?: number | null | undefined;
                workingHoursTo?: number | null | undefined;
                rooms?: number | null | undefined;
                beds?: number | null | undefined;
                quantity?: number | null | undefined;
                private?: boolean | null | undefined;
                kitchen?: boolean | null | undefined;
                bathroom?: boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                idOrSlug: string;
                data: {
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | undefined;
                    name?: string | number | boolean | null | undefined;
                    category?: string | number | boolean | null | undefined;
                    photo?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    photos?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    slug?: string | number | boolean | undefined;
                    description?: string | number | boolean | null | undefined;
                    priceDuration?: string | number | boolean | null | undefined;
                    workingHoursStart?: string | number | boolean | null | undefined;
                    workingHoursEnd?: string | number | boolean | null | undefined;
                    fiatPrice?: {
                        [x: string]: unknown;
                        val?: string | number | boolean | null | undefined;
                        cur?: string | number | boolean | null | undefined;
                    } | null | undefined;
                    fiatHourlyPrice?: {
                        [x: string]: unknown;
                        val?: string | number | boolean | null | undefined;
                        cur?: string | number | boolean | null | undefined;
                    } | null | undefined;
                    tokenPrice?: {
                        [x: string]: unknown;
                        val?: string | number | boolean | null | undefined;
                        cur?: string | number | boolean | null | undefined;
                    } | null | undefined;
                    tokenHourlyPrice?: {
                        [x: string]: unknown;
                        val?: string | number | boolean | null | undefined;
                        cur?: string | number | boolean | null | undefined;
                    } | null | undefined;
                    workingHoursFrom?: string | number | boolean | null | undefined;
                    workingHoursTo?: string | number | boolean | null | undefined;
                    rooms?: string | number | boolean | null | undefined;
                    beds?: string | number | boolean | null | undefined;
                    quantity?: string | number | boolean | null | undefined;
                    private?: string | number | boolean | null | undefined;
                    kitchen?: string | number | boolean | null | undefined;
                    bathroom?: string | number | boolean | null | undefined;
                    availableFor?: unknown[] | null | undefined;
                };
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                name?: string | null | undefined;
                category?: string | null | undefined;
                photo?: string | null | undefined;
                photos?: (string | null)[] | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                priceDuration?: string | null | undefined;
                workingHoursStart?: number | null | undefined;
                workingHoursEnd?: number | null | undefined;
                fiatPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                fiatHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                tokenHourlyPrice?: {
                    [x: string]: unknown;
                    val?: string | number | null | undefined;
                    cur?: string | null | undefined;
                } | null | undefined;
                workingHoursFrom?: number | null | undefined;
                workingHoursTo?: number | null | undefined;
                rooms?: number | null | undefined;
                beds?: number | null | undefined;
                quantity?: number | null | undefined;
                private?: boolean | null | undefined;
                kitchen?: boolean | null | undefined;
                bathroom?: boolean | null | undefined;
                availableFor?: unknown[] | null | undefined;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
    page: import("@trpc/server").TRPCBuiltRouter<{
        ctx: Context;
        meta: object;
        errorShape: {
            code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
            message: string;
            data: {
                code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
                httpStatus: number;
                path?: string;
                stack?: string;
                zodError: FlattenedZodError | null;
            };
        };
        transformer: false;
    }, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
        bySlug: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                slug: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                ogImage?: string | null | undefined;
                isStandard?: boolean | null | undefined;
                showInMenu?: boolean | null | undefined;
                menuSection?: string | null | undefined;
                menuLabel?: string | null | undefined;
                menuOrder?: number | null | undefined;
                menuSectionOrder?: number | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                needsPublishing?: boolean | null | undefined;
                publishedAt?: string | null | undefined;
                localizations?: unknown;
                _id: string;
            } | null;
            meta: object;
        }>;
        list: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                limit?: number | undefined;
                page?: number | undefined;
                sortBy?: string | undefined;
            } | undefined;
            output: (Record<string, never> | {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                ogImage?: string | null | undefined;
                isStandard?: boolean | null | undefined;
                showInMenu?: boolean | null | undefined;
                menuSection?: string | null | undefined;
                menuLabel?: string | null | undefined;
                menuOrder?: number | null | undefined;
                menuSectionOrder?: number | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                needsPublishing?: boolean | null | undefined;
                publishedAt?: string | null | undefined;
                localizations?: unknown;
                _id: string;
            })[];
            meta: object;
        }>;
        get: import("@trpc/server").TRPCQueryProcedure<{
            input: {
                id: string;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                ogImage?: string | null | undefined;
                isStandard?: boolean | null | undefined;
                showInMenu?: boolean | null | undefined;
                menuSection?: string | null | undefined;
                menuLabel?: string | null | undefined;
                menuOrder?: number | null | undefined;
                menuSectionOrder?: number | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                needsPublishing?: boolean | null | undefined;
                publishedAt?: string | null | undefined;
                localizations?: unknown;
                _id: string;
            };
            meta: object;
        }>;
        create: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                visibility?: "custom" | "private" | "public" | "secret" | undefined;
                channel?: string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null | undefined;
                visibleBy?: (string | number | boolean | string[] | {
                    [x: string]: unknown;
                    _id: string;
                } | null)[] | null | undefined;
                title: string | number | boolean | null;
                slug: string;
                description?: string | number | boolean | null | undefined;
                ogImage?: string | number | boolean | null | undefined;
                aiMeta?: "" | Record<string, unknown> | null | undefined;
                showInMenu?: string | number | boolean | null | undefined;
                menuSection?: string | number | boolean | null | undefined;
                menuLabel?: string | number | boolean | null | undefined;
                menuOrder?: string | number | boolean | null | undefined;
                menuSectionOrder?: string | number | boolean | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | undefined;
                    type: string;
                    data?: {
                        [x: string]: unknown;
                        background?: "" | "accent-light" | "dark" | "gradient-accent" | "gray-50" | "neutral-light" | "transparent" | "white" | null | undefined;
                        settings?: Record<string, unknown> | null | undefined;
                        content?: Record<string, unknown> | null | undefined;
                    } | undefined;
                }[] | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | undefined;
                    type: string;
                    data?: {
                        [x: string]: unknown;
                        background?: "" | "accent-light" | "dark" | "gradient-accent" | "gray-50" | "neutral-light" | "transparent" | "white" | null | undefined;
                        settings?: Record<string, unknown> | null | undefined;
                        content?: Record<string, unknown> | null | undefined;
                    } | undefined;
                }[] | undefined;
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                ogImage?: string | null | undefined;
                isStandard?: boolean | null | undefined;
                showInMenu?: boolean | null | undefined;
                menuSection?: string | null | undefined;
                menuLabel?: string | null | undefined;
                menuOrder?: number | null | undefined;
                menuSectionOrder?: number | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                needsPublishing?: boolean | null | undefined;
                publishedAt?: string | null | undefined;
                localizations?: unknown;
                _id: string;
            };
            meta: object;
        }>;
        update: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
                data: {
                    visibility?: "custom" | "private" | "public" | "secret" | undefined;
                    channel?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    visibleBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null)[] | null | undefined;
                    createdBy?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    interaction?: string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    } | null | undefined;
                    created?: string | number | undefined;
                    deleted?: string | number | null | undefined;
                    attributes?: unknown[] | null | undefined;
                    managedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | null | undefined;
                    reportedBy?: (string | number | boolean | string[] | {
                        [x: string]: unknown;
                        _id: string;
                    })[] | undefined;
                    slug?: string | undefined;
                    description?: string | number | boolean | null | undefined;
                    ogImage?: string | number | boolean | null | undefined;
                    aiMeta?: "" | Record<string, unknown> | null | undefined;
                    showInMenu?: string | number | boolean | null | undefined;
                    menuSection?: string | number | boolean | null | undefined;
                    menuLabel?: string | number | boolean | null | undefined;
                    menuOrder?: string | number | boolean | null | undefined;
                    menuSectionOrder?: string | number | boolean | null | undefined;
                    needsPublishing?: string | number | boolean | null | undefined;
                    publishedAt?: string | number | null | undefined;
                    localizations?: Record<string, unknown> | null | undefined;
                    title?: string | number | boolean | null | undefined;
                    sections?: {
                        [x: string]: unknown;
                        _id?: string | undefined;
                        type?: string | number | boolean | null | undefined;
                        data?: unknown;
                    }[] | null | undefined;
                    draftSections?: {
                        [x: string]: unknown;
                        _id?: string | undefined;
                        type?: string | number | boolean | null | undefined;
                        data?: unknown;
                    }[] | null | undefined;
                };
            };
            output: {
                visibility?: string | null | undefined;
                channel?: string | null | undefined;
                visibleBy?: (string | null)[] | null | undefined;
                createdBy?: string | null | undefined;
                interaction?: string | null | undefined;
                updated?: string | null | undefined;
                created?: string | null | undefined;
                attributes?: unknown[] | null | undefined;
                managedBy?: (string | null)[] | null | undefined;
                title?: string | null | undefined;
                slug?: string | null | undefined;
                description?: string | null | undefined;
                ogImage?: string | null | undefined;
                isStandard?: boolean | null | undefined;
                showInMenu?: boolean | null | undefined;
                menuSection?: string | null | undefined;
                menuLabel?: string | null | undefined;
                menuOrder?: number | null | undefined;
                menuSectionOrder?: number | null | undefined;
                sections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                draftSections?: {
                    [x: string]: unknown;
                    _id?: string | null | undefined;
                    type?: string | null | undefined;
                    data?: unknown;
                }[] | null | undefined;
                needsPublishing?: boolean | null | undefined;
                publishedAt?: string | null | undefined;
                localizations?: unknown;
                _id: string;
            };
            meta: object;
        }>;
        remove: import("@trpc/server").TRPCMutationProcedure<{
            input: {
                id: string;
            };
            output: {
                deleted: boolean;
            };
            meta: object;
        }>;
    }>>;
}>>;
export type AppRouter = typeof appRouter;

// models/page.constants.d.ts
export declare const STANDARD_PAGE_SLUGS: readonly ['/volunteer', '/cohousing', '/events', '/stay', '/token', '/subscriptions', '/citizenship', '/fundraiser', '/team', '/press'];
export declare const SECTION_BACKGROUNDS: readonly ['transparent', 'white', 'neutral-light', 'accent-light', 'gray-50', 'gradient-accent', 'dark'];
export declare const SLUG_PATTERN: RegExp;
export type StandardPageSlug = (typeof STANDARD_PAGE_SLUGS)[number];
export type SectionBackground = (typeof SECTION_BACKGROUNDS)[number];
export type PageSectionType = 'hero' | 'gallery' | 'testimonials' | 'stats' | 'features' | 'timeline' | 'collapsibleFaq' | 'richText' | 'cta' | 'media' | 'textBlock' | 'bookAStay' | 'staySearch' | 'listingsPreviews' | 'reviews' | 'upcomingEvents' | 'pastEvents' | 'events' | 'eventsCalendar' | 'tokenStats' | 'floatingBuyTokens' | 'supplyGraph' | 'priceHistory' | 'webinar' | 'citizenProgressBar' | 'financedTokensStart' | 'cohousingApplication' | 'volunteerCta' | 'dailyContribution' | 'subscriptionPlans' | 'fundraiser' | 'fundraiserProgress' | 'fundraiserMilestones' | 'fundraiserRewards' | 'teamStructure' | 'teamMembers' | 'teamDepartments' | 'teamPartners' | 'teamGovernance' | 'teamJoinCta' | 'pressStats' | 'pressPublications' | 'pressHighlights' | 'pressPodcasts' | 'pressContact';
export type HeroAlign = 'left' | 'right' | 'center' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
export type GalleryType = 'masonry';
export type GallerySize = 'standard' | 'large' | 'featured';
export type MediaType = 'image' | 'video';
export type TextBlockImagePosition = 'left' | 'right' | 'none';
export type FeatureVisualType = 'photo' | 'icon' | 'emoji' | 'none';
export type CtaStyle = 'default' | 'accent' | 'dark';
export type ColumnCount = 1 | 2 | 3 | 4 | 5;
export type TimelineStatus = 'current' | 'upcoming' | 'future' | 'done';

// index.d.ts
export type RouterInputs = inferRouterInputs<AppRouter>;
export type RouterOutputs = inferRouterOutputs<AppRouter>;
