import Head from 'next/head';
import Link from 'next/link';
import { NextPageContext } from 'next';
import { useTranslations } from 'next-intl';

import Heading from '../../components/ui/Heading';

import { loadLocaleData } from '../../utils/locale.helpers';

const SITE_URL = process.env.NEXT_PUBLIC_PLATFORM_URL || 'https://closer.earth';

const DigitalCommonsPage = () => {
  const t = useTranslations();

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'Digital Commons at Trillion-Dollar Scale',
    description: 'Open-source software creates $8.8 trillion in value. Wikipedia. DAOs managing billions. The digital age proves commons can work at unprecedented scale.',
    author: {
      '@type': 'Organization',
      name: 'Closer',
      url: SITE_URL,
    },
    publisher: {
      '@type': 'Organization',
      name: 'Closer',
      url: SITE_URL,
    },
    mainEntityOfPage: `${SITE_URL}/philosophy/digital-commons`,
    keywords: 'digital commons, open source software, Wikipedia, DAO, blockchain governance, Creative Commons, GitHub',
  };

  const stats = [
    {
      value: '$8.8T',
      label: 'Economic value generated by open-source software',
      source: 'Harvard Business School, 2024',
    },
    {
      value: '97%',
      label: 'Commercial software codebases containing open-source components',
      source: 'Synopsys OSSRA, 2025',
    },
    {
      value: '150M+',
      label: 'Developers collaborating on GitHub',
      source: 'GitHub, 2025',
    },
    {
      value: '$100B+',
      label: 'Total value locked in decentralized finance protocols',
      source: 'DeFi analytics, 2025',
    },
  ];

  return (
    <>
      <Head>
        <title>Digital Commons at Trillion-Dollar Scale | Closer Philosophy</title>
        <meta
          name="description"
          content="Open-source software creates $8.8 trillion in value. Wikipedia. DAOs managing billions. The digital age proves commons can work at unprecedented scale."
        />
        <meta name="keywords" content="digital commons, open source software, Wikipedia, DAO, blockchain governance, Creative Commons, GitHub, decentralized governance" />
        
        <meta property="og:title" content="Digital Commons at Trillion-Dollar Scale" />
        <meta property="og:description" content="Open-source software creates $8.8 trillion in value. Wikipedia. DAOs managing billions. The digital age proves commons can work at unprecedented scale." />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`${SITE_URL}/philosophy/digital-commons`} />
        <meta property="og:site_name" content="Closer" />
        
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Digital Commons at Trillion-Dollar Scale" />
        <meta name="twitter:description" content="Open-source software creates $8.8 trillion in value. The digital age proves commons can work at unprecedented scale." />
        
        <link rel="canonical" href={`${SITE_URL}/philosophy/digital-commons`} />
        
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </Head>
      <main className="w-full flex flex-col items-center gap-12 pb-20">
        <section className="flex flex-col items-center w-full max-w-[700px] gap-8 px-4">
          <Link
            href="/philosophy"
            className="self-start uppercase text-accent font-bold"
          >
            ◀️ {t('philosophy_back')}
          </Link>

          <Heading level={1} className="text-4xl text-center">
            {t('philosophy_digital_commons_title')}
          </Heading>

          <p className="text-lg text-center text-foreground/80">
            {t('philosophy_digital_commons_subtitle')}
          </p>
        </section>

        <section className="w-full max-w-[700px] px-4">
          <div className="grid sm:grid-cols-2 gap-4 mb-12">
            {stats.map((stat, index) => (
              <div
                key={index}
                className="bg-accent/10 rounded-lg p-6 text-center"
              >
                <p className="text-3xl font-bold text-accent mb-2">
                  {stat.value}
                </p>
                <p className="text-sm text-foreground/80 mb-1">{stat.label}</p>
                <p className="text-xs text-foreground/50">{stat.source}</p>
              </div>
            ))}
          </div>

          <div className="rich-text">
            <Heading level={2} className="text-2xl mb-4">
              The Invisible Foundation
            </Heading>
            <p className="text-lg leading-relaxed mb-6">
              The digital economy has quietly produced what may be
              history&apos;s largest-scale demonstration that commons governance
              can succeed—indeed, that it already underpins most of the modern
              technological infrastructure.
            </p>

            <p className="text-lg leading-relaxed mb-6">
              If firms had to build internally the open-source software they
              currently use for free, it would cost them $8.8 trillion. Yet
              recreating the most widely-used open-source projects would cost
              only $4.15 billion—revealing an extraordinary efficiency ratio
              where volunteer-coordinated commons production generates over
              2,000 times its replacement cost in demand-side value.
            </p>

            <div className="bg-foreground/5 rounded-lg p-6 my-8">
              <p className="text-lg">
                The Linux kernel alone—maintained by 11,089 contributors from
                1,780 organizations—runs 92% of cloud virtual machines on AWS,
                Google Cloud, and Azure, powers 59% of identifiable web servers,
                and underpins nearly every smartphone through Android.
              </p>
            </div>

            <Heading level={2} className="text-2xl mb-4 mt-10">
              Blockchain: Commons Governance for Value
            </Heading>
            <p className="text-lg leading-relaxed mb-6">
              If open-source software represents commons-based production,
              blockchain protocols represent commons-based governance of
              valuable shared resources. Decentralized autonomous organizations
              collectively manage $21-30 billion in treasury assets through
              token-weighted voting, delegation, and rough consensus
              mechanisms—essentially implementing Elinor Ostrom&apos;s design
              principles for commons governance at digital scale.
            </p>

            <p className="text-lg leading-relaxed mb-6">
              Bitcoin&apos;s 15-year governance track record demonstrates that
              leaderless, community-driven protocols can successfully navigate
              contentious decisions. Ethereum&apos;s transition to proof-of-stake
              in September 2022, the largest coordinated protocol upgrade in
              cryptocurrency history, was achieved through years of public
              debate, competing client teams, and ultimately validated by node
              operators choosing to run updated software.
            </p>

            <Heading level={2} className="text-2xl mb-4 mt-10">
              The Knowledge Commons
            </Heading>
            <p className="text-lg leading-relaxed mb-6">
              Wikipedia contains 66+ million articles across 342 languages—the
              sixth most-visited website globally, produced by approximately
              600,000 active editors who contribute 5.7 edits per second. A 2013
              economic valuation estimated Wikipedia&apos;s one-time replacement
              cost at $6.6 billion—yet the Wikimedia Foundation operates on
              approximately $185 million annually.
            </p>

            <p className="text-lg leading-relaxed mb-6">
              The Creative Commons licensing infrastructure has enabled
              approximately 2.5 billion works to be shared under standardized
              permissions across 9 million websites. OpenStreetMap, maintained
              by millions of volunteer contributors, powers navigation for
              Tesla, Grab, and Pokémon Go—another trillion-dollar infrastructure
              layer built through commons-based peer production.
            </p>

            <Heading level={2} className="text-2xl mb-4 mt-10">
              AGI: The Ultimate Test Case
            </Heading>
            <p className="text-lg leading-relaxed mb-6">
              If digital commons demonstrate the viability of collective
              ownership at scale, artificial general intelligence represents the
              most critical case for commons-based stewardship in human history.
            </p>

            <div className="bg-accent/10 border-l-4 border-accent p-6 my-8">
              <p className="text-lg">
                Indigenous perspectives offer distinctive frameworks. Te Hiku
                Media, a Māori nonprofit, developed te reo Māori speech
                recognition while implementing the Kaitiakitanga
                license—prohibiting use in applications that surveil,
                discriminate, or violate human rights. As CEO Peter-Lucas Jones
                articulates: &ldquo;Data is the new land.&rdquo;
              </p>
            </div>

            <p className="text-lg leading-relaxed mb-6">
              If AGI generates the transformative productivity gains that
              proponents anticipate, the question of who captures those
              gains—concentrated shareholders or distributed commons
              beneficiaries—may prove the defining political-economic question
              of the twenty-first century.
            </p>

            <Heading level={2} className="text-2xl mb-4 mt-10">
              Global Production, Local Benefit
            </Heading>
            <p className="text-lg leading-relaxed mb-6">
              GitHub now hosts over 150 million developers collaborating across
              193 countries—particularly rapid growth in Africa (Nigeria +28%,
              Kenya +33%) and Southeast Asia (Vietnam, Indonesia, Bangladesh
              +35%). This represents a genuine global commons of computational
              knowledge, governed through informal norms, code review processes,
              and community standards rather than corporate hierarchy.
            </p>

            <div className="bg-foreground/5 rounded-lg p-6 mt-10">
              <Heading level={3} className="text-xl mb-3">
                What This Proves
              </Heading>
              <p className="text-lg leading-relaxed">
                Digital commons at trillion-dollar scale directly contradict
                narratives of inevitable enclosure. Far from being pre-modern
                relics vulnerable to tragedy, commons governance now underpins
                most of the modern technological infrastructure—demonstrating
                that non-extractive collective ownership can operate at
                unprecedented scale.
              </p>
            </div>
          </div>
        </section>

        <section className="w-full max-w-[700px] px-4 pt-8 border-t border-divider">
          <Heading level={2} className="text-2xl mb-6">
            {t('philosophy_explore_more')}
          </Heading>
          <div className="flex flex-wrap gap-4">
            <Link
              href="/philosophy/commons-exclosure"
              className="btn-primary px-6 py-3"
            >
              {t('philosophy_commons_exclosure_title')}
            </Link>
            <Link
              href="/philosophy/shared-abundance"
              className="btn-primary px-6 py-3"
            >
              {t('philosophy_shared_abundance_title')}
            </Link>
          </div>
        </section>
      </main>
    </>
  );
};

export default DigitalCommonsPage;

DigitalCommonsPage.getInitialProps = async (context: NextPageContext) => {
  try {
    const messages = await loadLocaleData(
      context?.locale,
      process.env.NEXT_PUBLIC_APP_NAME,
    );
    return { messages };
  } catch (err) {
    return { error: err, messages: null };
  }
};
