import type { SectionType } from '../../types/page';

export const BLOCK_TYPE_LABEL_KEYS: Partial<Record<SectionType, string>> = {
  hero: 'pages_editor_block_hero',
  gallery: 'pages_editor_block_gallery',
  testimonials: 'pages_editor_block_testimonials',
  stats: 'pages_editor_block_stats',
  features: 'pages_editor_block_features',
  timeline: 'pages_editor_block_timeline',
  collapsibleFaq: 'pages_editor_block_collapsible_faq',
  richText: 'pages_editor_block_richtext',
  media: 'pages_editor_block_media',
  textBlock: 'pages_editor_block_text',
  cta: 'pages_editor_block_cta',
  bookAStay: 'pages_editor_block_book_a_stay',
  staySearch: 'pages_editor_block_book_a_stay',
  listingsPreviews: 'pages_editor_block_listings_previews',
  reviews: 'pages_editor_block_reviews',
  eventsCalendar: 'pages_editor_block_events_calendar',
  upcomingEvents: 'pages_editor_block_upcoming_events',
  pastEvents: 'pages_editor_block_past_events',
  events: 'pages_editor_block_upcoming_events',
  tokenStats: 'pages_editor_block_token_stats',
  floatingBuyTokens: 'pages_editor_block_floating_buy_tokens',
  supplyGraph: 'pages_editor_block_supply_graph',
  priceHistory: 'pages_editor_block_price_history',
  citizenProgressBar: 'pages_editor_block_citizen_progress',
  citizenshipStatus: 'pages_editor_block_citizenship_status',
  financedTokensStart: 'pages_editor_block_financed_tokens',
  cohousingApplication: 'pages_editor_block_cohousing_application',
  volunteerCta: 'pages_editor_block_volunteer_cta',
  projectList: 'pages_editor_block_project_list',
  dailyContribution: 'pages_editor_block_daily_contribution',
  subscriptionPlans: 'pages_editor_block_subscription_plans',
  fundraiser: 'pages_editor_block_fundraiser',
  fundraiserProgress: 'pages_editor_block_fundraiser_progress',
  fundraiserMilestones: 'pages_editor_block_fundraiser_milestones',
  fundraiserRewards: 'pages_editor_block_fundraiser_rewards',
  teamStructure: 'pages_editor_block_team_structure',
  teamMembers: 'pages_editor_block_team_members',
  teamDirectory: 'pages_editor_block_team_directory',
  teamDepartments: 'pages_editor_block_team_departments',
  teamPartners: 'pages_editor_block_team_partners',
  teamGovernance: 'pages_editor_block_team_governance',
  teamJoinCta: 'pages_editor_block_team_join_cta',
  pressStats: 'pages_editor_block_press_stats',
  pressPublications: 'pages_editor_block_press_publications',
  pressHighlights: 'pages_editor_block_press_highlights',
  pressPodcasts: 'pages_editor_block_press_podcasts',
  pressContact: 'pages_editor_block_press_contact',
  dataroom: 'pages_editor_block_dataroom',
  emailGate: 'pages_editor_block_email_gate',
  dataTable: 'pages_editor_block_data_table',
  documents: 'pages_editor_block_documents',
  barChart: 'pages_editor_block_bar_chart',
  flowDiagram: 'pages_editor_block_flow_diagram',
  webinar: 'pages_editor_block_webinar',
};

export const blockTypeLabelKey = (type: string): string =>
  BLOCK_TYPE_LABEL_KEYS[type as SectionType] ?? 'pages_editor_tab_block';
